name: Benchmark Specific Releases

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  benchmark-releases:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install ASV
        run: pip install asv

      - name: Show versions to benchmark
        run: |
          echo "Versions to benchmark:"
          cat versions.txt

      - name: Install scikit-bio dependencies
        run: |
          # Install dependencies needed to build scikit-bio from source
          pip install numpy scipy cython

      - name: Gather machine information
        run: |
          asv machine --yes

      - name: Run benchmarks
        run: |
            # this will run all benchmarks, except those which have been run before
            asv run HASHFILE:versions.txt --skip-existing-commits ALL

      - name: Generate HTML
        run: asv publish

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.asv/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Summary
        run: |
          echo "Benchmarking completed!"
          echo "Results deployed to: ${{ steps.deployment.outputs.page_url }}"
          echo "Current benchmark versions:"
          cat versions.txt
